### ISSUE TITLE
【p.csv】

### ISSUE THREAD

**Issue by linlin0026** [michel-mata/cNODE.jl#1]
Dear Professor, I learned your article and want to use it for my microbial data analysis, but I didn't find the example p.csv mentioned in the supplementary file. I'm not quite sure about its row arrangement, could you please add it? I will be very grateful. Meanwhile, I found the corresponding ID in the S4.3 In-vivo soil microbiome is 2104, not 2140.

**Comment by michel-mata** [comment]
Hi @linlin0026 , thank you for your comments!

This repository contains the package for general usage, so there is no data here. 
In [this repository](https://github.com/michel-mata/cNODE-paper) you will find the data for reproducing the paper. E.g., `Data/Experimental/Drosophila_Gut/P.csv`

In all the files we assume that the columns represent a local community, while the rows represent different taxa. So that 100 assemblages from a pool of 10 species would be a dataset of size 10x100.

**Comment by linlin0026** [comment]
Thanks for your help~
